# Generated by Django 4.2.2 on 2023-07-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paseador_cuidador',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
